### ISSUE TITLE
Swarm birds not displayed on Firefox

### ISSUE THREAD

**Issue by FabrizioRomanoGenovese** [swarmfund/sv-voting-mvp#114]
This is not big deal, but the animated swarm birds are not displayed in the background when using firefox (at least on whonix based machines). Only the orange background is displayed.

**Comment by TomSesselmann** [comment]
Hmm.. swarm birds seem to display fine in Firefox on OSX

<img width="1792" alt="screen shot 2017-10-25 at 9 09 03 am" src="https://user-images.githubusercontent.com/23013276/31970575-2d5095f4-b964-11e7-8e6d-71f10c631ed0.png">

**Comment by TomSesselmann** [comment]
@FabrizioRomanoGenovese I was going to ask if the swarm birds work for you on the main swarm.fund website, but I can't see any birds on the website anymore. There are some birds on the product site but I'm not sure if they are the same. They seem to behave slightly differently, but I may be wrong.
https://product.swarm.fund
