### ISSUE TITLE
[Meta, WIP] - Ballot (voting) specifics

### ISSUE THREAD

**Issue by XertroV** [swarmfund/sv-voting-mvp#3]
~~Which voting system are we using, and what are the parameters? (Range voting, approval, FPTP, etc)~~

We're using range voting as per Fab

Please provide the parameters for the vote:

* What are the short descriptions of the options?
* What are the long descriptions of the options?
* What is the description for the ballot overall?
* What does each option correspond to in regards to Swarm parameters?

This is fairly flexible and not high priority atm (not needed for the smart contract, just auditing suite), though we'll need to make sure the UI is constructed appropriately.

**Comment by Jazzwall** [comment]
➤ Jazzwall Sharad commented:

Let's get these answered tomorrow.  I'll confer with Fabrizio and Joel ahead of time.  Perhaps tomorrow afternoon my time (morning for you?).  Also, I take Joel's email summarizing this was not enough?

**Comment by Jazzwall** [comment]
@XertroV still working on this.  Fabrizio, Emi, and I will be working on answering this and then resolving with PP this weekend.  As per @fractastical 's email the four voting options as of now are:

1.   As in white paper (8 releases of 42 days each)
2.   More frequent (42 releases of 8 days each)
3.   Two year instead of one year time horizon (16 releases of 42 days each)
4.   Immediate (after 42 days all tokens are liquid)

**Comment by XertroV** [comment]
@Jazzwall - Cheers, we have them in the code now:

https://github.com/swarmfund/sv-voting-mvp/blob/3843ad3d361160003af042e64d8a2b6285cc6ac1/web/src/SecureVote/SPAs/SwarmMVP/Ballot.elm#L113

I also have made a template with exact specs in english, and added a comment to each one - this is up on the site under the "Details" buttons next to the ballots.

Example:

-----

### 8 releases of 42 days: Details

This option for the release of SWM tokens corresponds to the following specification:

* This release involves 8 releases over 42 days.
* At the conclusion of each 42 day period, approximately 12.50% of tokens will be released, proportionally across all token holders.
* This means the full liquidity release schedule will take 336 days to complete.

This is the proposal in the whitepaper. The release will take approximately 1 year.

**Comment by XertroV** [comment]
@Jazzwall if this looks good I'll close it up
