### ISSUE TITLE
[Meta, WIP] - Web UI user flow

### ISSUE THREAD

**Issue by XertroV** [swarmfund/sv-voting-mvp#5]
Basic idea thus far:
1. Input Address holding SWM tokens
2. Fill out ballot
3. Create tx to broadcast w/ validation instructions

See mockups for a rough idea of what I have in mind.

![mvp-1](https://user-images.githubusercontent.com/1046448/31387668-e7a08918-ae16-11e7-861f-f9291ff0f9ae.png)
![mvp-2](https://user-images.githubusercontent.com/1046448/31387669-e7d22e0a-ae16-11e7-8e72-92180bccc78e.png)
![mvp-3](https://user-images.githubusercontent.com/1046448/31387671-e80697b2-ae16-11e7-8720-7c910222a50f.png)

**Comment by Jazzwall** [comment]
➤ Jazzwall Sharad commented:

Ah, got it.  Perhaps relabel sub-experience as "verify your token holdings" and mark it as optional?

**Comment by XertroV** [comment]
Currently we have:

1. Eth Address
2. How to vote + explanation
3. Vote
4. Delegate
5. Cast

Dialogs:
* Info dialog: source code links, how to vote, how delegation + voting works
* Settings dialog: set a Web3 http provider
* Verify dialog: Instructions on verifying ballot

@Jazzwall the 1-5 should be done today, let me know if you have feedback or anything needs changing
