### ISSUE TITLE
Mobile?

### ISSUE THREAD

**Issue by XertroV** [swarmfund/sv-voting-mvp#66]
@Jazzwall - do we care about providing a mobile UI?

My thoughts at the moment are that this would be mildly counterproductive - we'd need to figure out support for mobile wallets, and I'm not sure how good they are with anything besides QR codes (and we can do a QR code quite easily). Most ppl (I hope) are holding their tokens on a Trezor (or similar) and probably use MEW, or Geth, or something like that.

The voting UI might suffer a bit as well, though we can probably work around it with vertical spacing.

Given Ethereum's poor user experience for the most part I _presume_ most heavy stuff still goes on via a PC/Laptop.

**Comment by Jazzwall** [comment]
➤ Jazzwall Sharad commented:

Hey Max, for the MVP, I think it's fine to stick with the desktop UI unless you can deliver a mobile UI in time as well.  Can we tag that as a "nice to have" feature in case you guys have time left?
